fix reset password error messages
loopstudio/rails-api-boilerplate pull request #214
Opened 2020-09-09 21:37 UTC by diebas

#### Description:

The reset_password_token_expired error was called when the token expired and when user entered a bad token. It wasn't specified on the languages files also so I defined an invalid_reset_password_token error instead.

On the update method of the password controller it was executing `errors[:reset_password_token].any?`, for some reason, this line was adding `reset_password_token: []` to error.messages where it wasn't before. Instead of asking for the value inside the key, now I'm asking if the key is present to prevent the described before to happen.

---

#### :pushpin: Notes:

* Not sure on how to add tests for this as

---

#### :heavy_check_mark:Tasks:

* Add invalid_reset_password_token error
* Fix update password error response message
* Add tests

---

@loopstudio/ruby-devs

2020-09-10 12:13 UTC, lucaleivaloop approved these changes

2020-09-10 13:27 UTC, mwolman requested changes

2020-09-10 13:27 UTC, mwolman commented on config/locales/es.yml
> +    reset_password_token_invalid: 'el token para el reseteo de contraseña no es valido'
Can you move this translation below `page_not_found` to have the same order as the `en.yml` file?

2020-09-10 13:27 UTC, mwolman commented on config/locales/es.yml
> +    reset_password_token_invalid: 'el token para el reseteo de contraseña no es valido'
```suggestion
    reset_password_token_invalid: 'el token para restablecer la contraseña no es válido'
```

2020-09-15 15:15 UTC, mwolman approved these changes

2020-09-15 16:58 UTC, merged