run linters on all files
loopstudio/rails-api-boilerplate pull request #311
Opened 2021-01-22 19:08 UTC by diebas

#### :link: Board reference:

* [Include all files while running linters](https://loopstudio.atlassian.net/jira/software/projects/API/boards/12?selectedIssue=API-105)

---

#### Description:

Linters where running only on the diff files, in certain cases this make the checks to fail. This pr make the linters run on the whole app as discussed on the tech council.

---

#### :pushpin: Notes:

* This changes would make effect both locally and on github actions

---

@loopstudio/ruby-devs

2021-01-22 19:15 UTC, mconiglio commented on lib/tasks/linters.rake
>    if files_diff.present?
I think we should run this regardless the files_diff presence

2021-01-22 19:17 UTC, mwolman requested changes

2021-01-22 19:17 UTC, mwolman commented on lib/tasks/linters.rake
>    if files_diff.present?
We don't need this check anymore, neither the `files_dif` variable

2021-02-02 16:14 UTC, mwolman approved these changes

2021-02-03 13:42 UTC, cindy-a approved these changes

2021-02-03 19:20 UTC, mconiglio approved these changes

2021-02-03 19:40 UTC, merged